version: "3.7"

services:
  db:
    image: postgres:11.4
    ports: 
      - 5432:5432
    hostname: <%= projectName %>
    environment:
      POSTGRES_DB: <%= projectName %>
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  .volumes: